FROM php:5.6-apache

ARG DDTRACE_VERSION
ARG WEB_APP_PATH

RUN apt-get update \
# Install base packages
    && apt-get install -y \
        curl \
        wget \
        mysql-client \
        git \
        gnupg2 \
        zlib1g-dev \
        unzip \
        libmcrypt-dev \
        vim \
# Install relevant php extensions
    && docker-php-source extract \
    && docker-php-ext-install mcrypt \
    && docker-php-ext-install pdo_mysql \
    && docker-php-ext-install pdo \
    && docker-php-ext-install zip \
    && docker-php-source delete \
# Install composer
    && php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
    && php composer-setup.php  --install-dir="/usr/bin" --filename=composer \
    && php -r "unlink('composer-setup.php');" \
    && composer self-update \
# Remove installation cache
    && rm -rf /var/lib/apt/lists/*

# Install DDTrace deb
RUN wget -O datadog-php-tracer.deb https://github.com/DataDog/dd-trace-php/releases/download/${DDTRACE_VERSION}/datadog-php-tracer_${DDTRACE_VERSION}-beta_amd64.deb \
    && dpkg -i datadog-php-tracer.deb

RUN a2enmod rewrite

COPY Dockerfiles/apache2.conf /etc/apache2/apache2.conf
COPY Dockerfiles/apache2-virtualhost.conf /etc/apache2/sites-available/000-default.conf

COPY ${WEB_APP_PATH} /var/www

WORKDIR /var/www

RUN chmod -R a+w /var/www

RUN composer update

CMD [ "apache2-foreground" ]
