
ENV["FLASK_APP"] = "flaskr.py"

task :db do
  sh "flask initdb"
end

task :run => :db do
  sh "python flaskr.py"
end

task :uwsgi => :db do
  sh  "uwsgi -p 4 --http :9090 --manage-script-name --mount /=flaskr:app --enable-threads --thunder-lock"
end

task :default => :run
