# Copyright 2024-Present Datadog, Inc. https://www.datadoghq.com/
# SPDX-License-Identifier: Apache-2.0

receivers:
  otlp:
    protocols:
       # specifying 0.0.0.0 allows the otel-collector to be accessed from the host machine as well
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 10s

  transform:
    error_mode: ignore
    trace_statements:
      - context: span
        conditions:
          - name != nil
        statements:
          - set(attributes["resource.name"], name)

exporters:
  debug:
    verbosity: detailed

  datadog/api:
    hostname: customhostname

    # tags:
    #   - example:tag

    api:
      key: ${DATADOG_API_KEY}

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [transform, batch]
      exporters: [debug, datadog/api]
