
task :run do
  sh "python manage.py runserver 0.0.0.0:8000"
end

task :migrate do
  sh "python manage.py migrate"
end

task :user do
  sh "python manage.py createsuperuser --username admin --email admin@example.com"
end

task :setup => [:migrate, :user]

task :default => [:run]
