version: "3"
services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel-collector-config.yml"]
    ports:
      - "55680:55680/tcp"
      - "55681:55681/tcp"
      - "55678:55678/tcp"
      - "14268:14268/tcp"
      - "4317:4317/tcp"
      - "4318:4318/tcp"
      - "9411:9411/tcp"
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
  python-microservice:
    build:
      context: python-microservice
      dockerfile: Dockerfile
    environment:
      # The spec says this should include http or https but python appears to have implemented differently
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:55680
      - OTEL_RESOURCE_ATTRIBUTES=deployment.environment=otel_sandbox,version=v1
    depends_on:
      - otel-collector
      - node-microservice
      - mongo
      - fluent-bit
    logging:
      driver: fluentd
      options:
        # Allow time for otel-collector to spin up, then forward fluentd logs to the fluentforwarder receiver.
        fluentd-async-connect: "true"
        # Use nanosecond precision
        fluentd-sub-second-precision: "true"
  node-microservice:
    build:
      context: node-microservice
      dockerfile: Dockerfile
    environment:
      # opentelemetry-js only has json over http at this time 
      - OTEL_EXPORTER_OTLP_HTTP_ENDPOINT=otel-collector:55681
      - OTEL_RESOURCE_ATTRIBUTES=deployment.environment=otel_sandbox,version=v1
    depends_on:
      - otel-collector
      - ruby-microservice
      - mongo
    logging:
      driver: fluentd
      options:
        # Allow time for otel-collector to spin up, then forward fluentd logs to the fluentforwarder receiver.
        fluentd-async-connect: "true"
        # Use nanosecond precision
        fluentd-sub-second-precision: "true"
  ruby-microservice:
    build:
      context: ruby-microservice
      dockerfile: Dockerfile
    environment:
      # was having trouble with the otlp export but jaeger also exists in core by default
      - OTEL_EXPORTER_JAEGER_ENDPOINT=http://otel-collector:14268/api/traces
      - OTEL_RESOURCE_ATTRIBUTES=deployment.environment=otel_sandbox,version=v1
      - OTEL_TRACES_EXPORTER=jaeger
    depends_on:
      - otel-collector
      - mongo
      - redis
    logging:
      driver: fluentd
      options:
        # Allow time for otel-collector to spin up, then forward fluentd logs to the fluentforwarder receiver.
        fluentd-async-connect: "true"
        # Use nanosecond precision
        fluentd-sub-second-precision: "true"
  vegeta:
    container_name: vegeta
    image: peterevans/vegeta
    command: sh -c "echo 'GET http://python-microservice:5000/' | vegeta attack -rate=1 -duration=15m"
    depends_on:
      - python-microservice
      - fluent-bit     
  mongo:
    image: mongo:3.5
    container_name: mongo
    ports:
      - "27017:27017/tcp"
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379/tcp"
  fluent-bit:
    image: fluent/fluent-bit
    volumes:
      - ./fluent-bit/parsers.conf:/fluent-bit/etc/parsers.conf
      - ./fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
    ports:
      - "24224:24224" # fluentd
      - "24224:24224/udp" # fluentd
