extensions:

receivers:
  otlp:
    protocols:
       # specifying 0.0.0.0 allows the otel-collector to be accessed from the host machine as well
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

  jaeger:
    protocols:
      thrift_http:

  zipkin:

processors:
  batch:
    timeout: 10s

exporters:
  debug:
    verbosity: detailed

  datadog/api:
    hostname: customhostname

    # tags:
    #   - example:tag

    api:
      key: <YOUR_API_KEY>

service:
  pipelines:
    traces:
      receivers: [otlp, zipkin, jaeger]
      processors: [batch]
      exporters: [debug, datadog/api]
