FROM alfa30/laravel:4.2

ENV DDTRACE_VERSION 0.4.0

RUN apt-get update && apt-get install -y wget

RUN docker-php-ext-install pcntl

RUN wget -O datadog-php-tracer.deb https://github.com/DataDog/dd-trace-php/releases/download/${DDTRACE_VERSION}/datadog-php-tracer_${DDTRACE_VERSION}-beta_amd64.deb
RUN dpkg -i datadog-php-tracer.deb && apt-get install -f
RUN php -m | grep ddtrace

RUN composer self-update

RUN composer require opentracing/opentracing
RUN composer require datadog/dd-trace
