FROM richarvey/nginx-php-fpm:php5

#
ENV DDTRACE_VERSION 0.4.0
#
#RUN apt-get update && apt-get install -y wget
#
#RUN docker-php-ext-install pcntl
#
RUN wget -O /tmp/datadog-php-tracer.apk https://github.com/DataDog/dd-trace-php/releases/download/${DDTRACE_VERSION}/datadog-php-tracer_${DDTRACE_VERSION}-beta_noarch.apk
RUN apk update && apk add /tmp/datadog-php-tracer.apk
RUN php -m | grep ddtrace
#
## Nginx
#RUN apt-get install -y nginx
#COPY php56_nginx.conf /etc/nginx/sites-available/default
#
#RUN composer self-update
#
#WORKDIR /var/www

