source 'https://rubygems.org'
ruby "2.1.7"

gem 'connection_pool'
gem 'json'
gem 'redis'
gem 'sinatra'
gem 'sinatra-contrib'

# tracing
gem 'ddtrace', '0.7.1.pre.944', :source => 'http://gems.datadoghq.com/trace-dev/'
