source 'https://rubygems.org'
ruby "2.1.7"

gem 'connection_pool'
gem 'json'
gem 'redis'
gem 'sinatra'
gem 'sinatra-contrib'

# tracing
gem 'ddtrace', :git => 'https://github.com/DataDog/dd-trace-rb.git', :ref => '12cdddbc3272bcbc4e4c650c222ee819da6947c2'
