source 'https://rubygems.org'
ruby "2.1.7"

gem 'connection_pool'
gem 'json'
gem 'redis'
gem 'sinatra'
gem 'sinatra-contrib'

gem 'ddtrace', :git => 'https://github.com/DataDog/dd-trace-rb', :ref => '8dcff9b3b5569f8289be4907d9fcbf98ddf529f2'
