source 'https://rubygems.org'

# branch with MongoDB Ruby Driver instrumentation
gem 'ddtrace', :git => 'https://github.com/DataDog/dd-trace-rb.git', :ref => '2efc51aceb69a3a9ca2fb51817879877bb41e951'
gem 'mongoid', '5.1.0'

# rails gems
gem 'rails', '4.2.9'

# application server
gem 'unicorn'
