# frozen_string_literal: true

source 'https://rubygems.org'

ruby '2.6.3'

# Use Puma as the app server

gem 'puma', '~> 3.11'
gem 'redis-sinatra'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'spacex'
gem 'opentelemetry-instrumentation-all'
gem 'opentelemetry-sdk'
gem 'opentelemetry-api'
gem 'opentelemetry-exporter-otlp'
gem 'opentelemetry-exporter-jaeger'

