version: '3.7'

services:

  agent:
    image: datadog/agent:latest
    ports:
      - 8125:8125
      - 8126:8126
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    environment:
      - DD_API_KEY=${DATADOG_API_KEY}
      - DD_APM_ENABLED=true
      - DD_APM_ENV=trace_examples_java

  java:
    image: java:8-jdk
    volumes:
      - ./:/var/trace-examples
      - gradle-cache:/root/.gradle
    working_dir: /var/trace-examples
    depends_on:
      - agent
    ports:
      - 8080:8080
    environment:
      DD_AGENT_HOST: agent
    command: "./gradlew :spring-app:bootRun"

volumes:
  gradle-cache:
